### ISSUE TITLE
I get dizzy because of the camera zoom

### ISSUE THREAD

**Issue by Sandruski** [NOREADMEStudios/ProjectII#82] opened 2018-05-07 11:48 UTC
I don't know where the camera will go, how much it will zoom... I can't predict anything and all this crazy zoom in zoom out makes me feel very dizzy while playing. I can't enjoy the gameplay because of this.

**Comment by dynamiczero99** [comment] 2018-05-19 16:28
Duplicate of #80 and #76.

**Closed as completed by dynamiczero99** 2018-05-19 16:28 UTC
Labels: duplicate
